### ISSUE TITLE
Add a Switch to Control Protocol Fee

### ISSUE THREAD

**Issue by kingster-will** [storyprotocol/protocol-core-v1#199]
## Description

We need to implement a switch to control whether the Protocol Fee is charged, similar to the mechanism used in Uniswap. This switch will be controlled by Governance and should be turned off at the beginning of the mainnet deployment. It will be turned on through the Governance process at a later stage.

## Objectives

- **Implement Protocol Fee Switch**: Add a switch to control the charging of the Protocol Fee.
- **Governance Control**: Ensure the switch can be turned on or off by Governance.
- **Initial State**: The switch should be turned off at the beginning of the mainnet deployment.

## Acceptance Criteria

- A boolean variable representing the Protocol Fee switch is added.
- Functions to control the switch are implemented and can only be called by Governance.
- The switch is set to off in the initial deployment.
- All tests pass, confirming the correct implementation and control of the switch.
- Documentation is updated to reflect the new feature.

**Comment by Ramarti** [comment]
There are several places this fee can be set

For royalty related payments: Fee will be a % of whatever ERC20 is used in payment
- On `mintFee`
- On `payRoyaltyOnBehalf`
- When `claiming` from vaults: If we do this one we shouldn't do previous 2

For registration fee of any asset, commercial or not, we need to define
- Flat fee
- Denomination (native token, ERC20s)

**Comment by kingster-will** [comment]
Royalty fee switch added in PR #243
