### ISSUE TITLE
M-2 Register derivative to block adding to the group

### ISSUE THREAD

**Issue by rvierdiiev** [storyprotocol/protocol-core-v1#287]
## Description
In order to add IPs to the group, [it should have no derivatives or minted license tokens](https://github.com/storyprotocol/protocol-core-v1/blob/3ef2a99a99192587d24b4805d5848e3a799dcf5e/contracts/modules/grouping/GroupingModule.sol#L240-L247). The logic is once first payment is received, then members should not be changed.

Once group IP is registered, then it supports default license term and anyone can use it to become a derivative. This can be used to block group members managing.

## Recommendation
We are still thinking about the solution.

**Comment by irfand29** [comment]
Nice
