### ISSUE TITLE
H-1 Group member IP can repeatedly claim rewards

### ISSUE THREAD

**Issue by berndartmueller** [storyprotocol/protocol-core-v1#288]
## Description and context

Group member IPs can claim royalty rewards with [`GroupingModule.claimReward()`](https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/modules/grouping/GroupingModule.sol#L194). The IP ID addresses are supplied via the `address[] calldata ipIds`.  Note that this array can contain duplicates!

Then, internally [`EvenSplitGroupPool.distributeRewards()`](https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/modules/grouping/EvenSplitGroupPool.sol#L123-L143)  is called which [calculates](https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/modules/grouping/EvenSplitGroupPool.sol#L165-L186) the rewards share for the IPs by looping `ipIds`. This loop potentially attempts to account for already claimed rewards by `rewardPerIP - $.ipRewardDebt[groupId][token][ipIds[i]]`.

However, this reward calculation by `_getAvailableReward()`  is done **before** `$.ipRewardDebt` is [updated](https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/modules/grouping/EvenSplitGroupPool.sol#L139). This allows repeatedly claiming rewards for the same IP address, more than it would be eligible for, a.k.a stealing funds from others.

## Solution recommendation

Prevent duplicate items in `ipIds` to be passed to `distributeRewards(..)`.

**Comment by mehtabmastoi74-coder** [comment]
Your IP: 103.244.178.197, the reward has already been claimed by member ID: 744378345. The limit for the number of people claiming the reward from the same IP has been reached, so you cannot participate in this event.
