### ISSUE TITLE
H-2 Front-running group registrations prevents registering groups

### ISSUE THREAD

**Issue by berndartmueller** [storyprotocol/protocol-core-v1#289]
## Description and context

A new group is registered via [`GroupingModule.registerGroup()`](https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/modules/grouping/GroupingModule.sol#L116). Internally, the group NFT token id is minted and the group registered via `GroupIPAssetRegistry.registerGroup()` . This calls `_register(..)` in https://github.com/storyprotocol/protocol-core-v1/blob/1efaf9e53754c3d2fce583a5867ced2ec299c36a/contracts/registries/GroupIPAssetRegistry.sol#L58
which is the same as when registering a regular IP asset.

It is possible to front-run group registrations by using the same group NFT contract + token ID to register as a regular IP asset. This would prevent registering the group. 

And as the groups use sequential token IDs for the group NFT tokens, using such a group NFT token id incorrectly as an IP asset, it would make it impossible to register a group with the same ID and thus prevents registering groups at all.

## Solution recommendation

One possibility to fix this issue would be checking in `_register(..)` if the NFT contract + token ID already exists, as the group NFT is minted as part of the registration. Note that such a check in the current implementation would also affect regular IP asset registration.

**Comment by kingster-will** [comment]
In the current implementation, calling `_register(...)` will revert with an `ERC721NonexistentToken` error if the specified tokenId does not exist, as it checks for the owner of the `tokenId`.

https://github.com/storyprotocol/protocol-core-v1/blob/c1b0f11f7ad41a3525b13ca09423e87be5ee2d93/contracts/registries/IPAssetRegistry.sol#L196

```solidity
        if (IERC721(tokenContract).ownerOf(tokenId) == address(0)) {
            revert Errors.IPAssetRegistry__InvalidToken(tokenContract, tokenId);
        }
```

However, making IP registration idempotent would be preferable to prevent such issues.
