### ISSUE TITLE
PILTerms Offchain Metadata Storage

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#48]
Many PILTerms are stored offchain as they are used for dispute resolutions. Hence, those offchain terms should be linked to their onchain PILTerms struct via a URI field in PILTerms.

**Comment by LeoHChen** [comment]
don't we have a URI for license token already? @kingster-will

**Comment by kingster-will** [comment]
Yes, the License Token has a URI.

**Comment by jdubpark** [comment]
Can you show where it has the URI to the offchain storage of license terms, can't seem to find it myself.

Also, how do we, to our best effort, enforce the content of the offchain storage of license terms?

**Comment by jdubpark** [comment]
superseded by #77
