### ISSUE TITLE
Remove Global Permission in IP Access Control

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#57]
The old IP ACL system required each IP Account to allow module-to-module (M2M) calls, such as the Licensing Module calling the Royalty Module. To remove this ACL friction, global permission was introduced where the first mapping `ipAccount` was set to `address(0)` by the protocol governance to indicate a wildcard.

However, using the IP-specific ACL system for M2M interactions introduces potential security risks as well as unintended side consequences of using a wildcard. Hence, we should remove the global permission.

Then, to facilitate the core M2M interactions, which are known in advance, we should use custom, per-module modifiers to gate calls to functions. While this fulfills the requirement handled by the global permission, it can be structurally improved with a dedicated ACL for M2M calls (at the expensive of slightly higher gas cost).

**Comment by LeoHChen** [comment]
Fixed in https://github.com/storyprotocol/protocol-core-v1/pull/89
