### ISSUE TITLE
Remove unused/redundant code in AccessControlled

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#62]
## Remove `onlyIpAccount`
**Rationale**: It's not used in any part of the core protocol (only used in a mock for tests).

https://github.com/storyprotocol/protocol-core-v1/blob/d6ca84fc3ebd5637cab6a390def6ffc426766085/contracts/access/AccessControlled.sol#L39-L44

## Remove redundant checks in `_verifyPermission`
**Rationale**: The IP Access Controller is tasked with checking permission. Thus, the extra checks in `_verifyPermission` are redundant.

https://github.com/storyprotocol/protocol-core-v1/blob/d6ca84fc3ebd5637cab6a390def6ffc426766085/contracts/access/AccessControlled.sol#L60-L69

_should simply be_

```solidity
function _verifyPermission(address ipAccount) internal view {
    ACCESS_CONTROLLER.checkPermission(ipAccount, msg.sender, address(this), msg.sig);
}
```

## Remove redundant checks in `_hasPermission`
**Rationale**: Same as above, redundant checks in `_hasPermission`. Simply call `checkPermission` with try-catch.

https://github.com/storyprotocol/protocol-core-v1/blob/d6ca84fc3ebd5637cab6a390def6ffc426766085/contracts/access/AccessControlled.sol#L75-L89

_should simply be_

```solidity
function _hasPermission(address ipAccount) internal view returns (bool) {
    try ACCESS_CONTROLLER.checkPermission(ipAccount, msg.sender, address(this), msg.sig) {
        return true;
    } catch {
        return false;
    }
}
```

**Comment by kingster-will** [comment]
They are NOT unused or redundant code.

`onlyIpAccount` modifier is for the restriction function can only be access by IPAccount, we provide it as a platform to ecosystem.
The logic in `_verifyPermission` and `_hasPermission` avoid duplicate efforts of checking permissions. the logic is needed.

**Comment by jdubpark** [comment]
I see a fundamental flaw in ACL flow, which now requires the extra checks in AccessControlled, thus effectively making it a package deal with AccessController for the protocol to use the IP ACL system. 

I'll close this issue for now. However, I want to note that ACL flow should be designed such that there should not be "duplicate efforts" in the first place (which led to the extra checks in AccessControlled).
