### ISSUE TITLE
Allow Specifying the Mint Fee Receiver

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#67]
Currently, fees paid for minting License Tokens flow to the licensor IP. However, there are some use-case requests where the mining fee should flow to an external address.

In other words, we should allow an IP owner or its delegate to specify the minting fee receiver, which will be used in `_payMintingFee`.

https://github.com/storyprotocol/protocol-core-v1/blob/5d2eb00452e48ee9199d22e983db442383234e46/contracts/modules/licensing/LicensingModule.sol#L168

**Comment by kingster-will** [comment]
<img width="1002" alt="Screenshot 2024-04-11 at 13 12 52" src="https://github.com/storyprotocol/protocol-core-v1/assets/83567446/e7251165-b102-4206-9a1c-2291cb586d37">
Per the current design, the minting fee payment must go through RoyaltyModule according to RoyaltyPolicy. 
LicensingModule make mintingFee payment by call through RoyaltyModule. Does RoyaltyModule support EOA as a minting fee receiver? @Spablob

**Comment by Spablob** [comment]
After discussion - this is resolved given that users can send the royalty tokens to an address of their choosing and that address automatically becomes the receiver of future royalty revenue inflows
