### ISSUE TITLE
Add territories and distributions for PIL Terms

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#79]
Territories and distributions are necessary for compatibility checks. It was previously supported in beta but removed with PR #33.

Example:
- PIL License 1 only allows distribution via movies & in Asia (territory)
- PIL License 2 only allows distribution via cartoons & in USA (territory)

These two PIL licenses are not compatible, so must be checked onchain.

**Comment by LeoHChen** [comment]
These two were removed as they are not enforceable on-chain. Requested by @jzhao23 .

**Comment by jdubpark** [comment]
Yes, not enforceable onchain but still needs compatibility check.

We can't have a child inherit from two parents whose territories and/or distribution channels are different.

We need to check that either
- List of territory/distribution is empty
- If not, make sure they are equal between license terms from parents

**Comment by jdubpark** [comment]
We can store the hash of each list, per @Ramarti's suggestion some time ago.

I think distribution & territories are crucial terms to licenses, thus it's worth checking these onchain. Especially since IP market is very strict on which distribution & territories a license is valid in.

**Comment by LeoHChen** [comment]
@jzhao23 please voice in the direction.

**Comment by jdubpark** [comment]
Marking this as solved if #77 is passed.

The main issue is having a value distinguisher between
- PIL License 1 only allows distribution via movies & in Asia (territory)
- PIL License 2 only allows distribution via cartoons & in USA (territory)

to generate unique IDs for these different licenses.

As proposed in #77, the offchain URI field in PILTerms will be that value distinguisher.

Otherwise, we will face ID collision for PILTerms with different offchain term values.

**Comment by LeoHChen** [comment]
Shall be resolved in https://github.com/storyprotocol/protocol-core-v1/issues/77
