### ISSUE TITLE
PILicenseTemplate is not upgradeable

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#81]
## Issue

Neither PILicenseTemplate nor BaseLicenseTemplateUpgradeable inherits UUPSUpgradeable.

Preferably BaseLicenseTemplateUpgradeable inherits UUPSUpgradeable. 

(PILicenseTemplate inherits BaseLicenseTemplateUpgradeable)

**Comment by Ramarti** [comment]
BaseLicenseTemplateUpgradeable is abstract so not UUPSUpgradeable.
UUPSUpgradeable is the one authorizing the upgrade, so it must be top level contract.
PILicenseTemplate is a mistake, will fix.
Good catch!
