### ISSUE TITLE
Anyone can write to any IPAccounts using their namespace

### ISSUE THREAD

**Issue by jdubpark** [storyprotocol/protocol-core-v1#84]
Anyone can write to any IPAccounts using their namespace (`msg.sender`), for example,
```solidity
function setBytes(bytes32 key, bytes calldata value) external {
    bytesData[_toBytes32(msg.sender)][key] = value;
}
```

We can either
1. Keep this freedom (will attract spams to IPAccount storage)
2. Restrict to permissioned writers, such as registered modules and registries.

Reading will remain 100% public.

**Comment by LeoHChen** [comment]
As discussed, we will allow only registered modules writing to IPA for now.
